### ISSUE TITLE
ExtractedData has surprising behavior

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/intellij-ui-test-robot#10]
1. `hasText` has some interesting behavior due to it caches the data and only refreshes in negative conditions.

The code:
```
waitFor { comp.hasText("loading...") == false }
```
will run forever since it will only refresh the data if it can't be found. 

Meaning using it against an AsyncTreeModel will run the risk of an infinitive loop even after the tree has been loaded.

You instead have to do `findAll().any()`, which is fine but not obvious without reading the actual source.

This is made worse by Fixture sometimes using this method depending on its `hasText` signature:

```
  fun hasText(txt: String): Boolean = data.hasText(txt)
  fun hasText(filter: (TextData) -> Boolean): Boolean = data.getMany(filter).isNotEmpty()
  fun hasText(textPredicate: Predicate<TextData>): Boolean = data.getMany { textPredicate.test(it) }.isNotEmpty()
```

2. `getAll` and `getOne` will never refresh the data, instead you need to call `getMany`. `getMany` is what Fixture delegates to though, so that is less of an issue but still confusing.

**Comment by abrooksv** [comment]
I am happy to submit a PR, just not sure what way you want to handle this.

Should `Fixture.hasText(txt: String)` be using `getMany` like the other impls and deprecate `ExtractedData#hasText`?

Should we just change the `get*` methods to always refresh?

**Comment by nizienko** [comment]
Thanks! There was an idea to cache already found texts in case of performance issues. It turned out that it's not that usable when we waiting for some text or when position of text changes. It seems that it will work quick enough if we refresh text on every get method.

**Comment by abrooksv** [comment]
Cool, will get that changed and PR'ed tomorrow.
