### ISSUE TITLE
Failed to find 'JPopupMenuFixture' when used for 'Project SDK' dropdown menu

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#104]
- the WaitForConditionTimeoutException is thrown when the RR framework fails to find 'JPopupMenuFixture'
- this exception appear only sometime (on macOS Catalina 10.15 and on macOS Big Sur 11 - in both cases on github actions) other platforms are ok

**This code causes sometimes WaitForConditionTimeoutException:**
`JPopupMenuFixture projectSdkList = find(JPopupMenuFixture.class, JPopupMenuFixture.Companion.byType(), Duration.ofSeconds(10));`

**This code works without issue:**
`ComponentFixture projectSdkList = find(ComponentFixture.class, byXpath("//div[@class='HeavyWeightWindow']"), Duration.ofSeconds(10));`

<img width="866" alt="130352872-50b5fa7e-b6e3-45da-8e4f-d6b07faa2f95" src="https://user-images.githubusercontent.com/43820055/135653154-63ec5269-e936-4f1d-adc9-36ccbce2ff15.png">

**Comment by mkfl3x** [comment]
Hello @zcervink, 
New HeavyWeightWindowFixture was added

**Comment by bric3** [comment]
Hi,

In my case I was able to get a reference to the `HeavyWeightWindowFixture`, however I can't get the content of the selected items. In the particular case of JDK, we might have to wait a bit, I'll try tomorrow.

**Comment by zcervink** [comment]
@mkfl3x The usage of `HeavyWeightWindowFixture` did resolve my issue and I am using that now in my UI tests. And @bric3 has a point - that issue appears because IDEA is still searching for more SDKs and just wait resolves the issue. Additionally to that there is issue https://github.com/JetBrains/intellij-ui-test-robot/issues/83 describing usage of `HeavyWeightWindowFixture` and the IdeaSideException that appears after clicking on it. The same thing - just waiting until the search is complete resolves the issue.
