### ISSUE TITLE
ComponentLookupException while trying to access ComboBox using build in fixture

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#106]
**Code that throws ComponentLookupException:**
`ComponentFixture projectJdkComboBox = comboBox(byXpath("//div[@accessiblename='Project SDK:' and @class='JPanel']"), Duration.ofSeconds(10));`

**Code that also throws the same ComponentLookupException:**
`ComboBoxFixture projectJdkComboBox = findAll(ComboBoxFixture.class, byXpath("//div[@accessiblename='Project SDK:' and @class='JPanel']")).get(0);`

**Code that works:**
`ComponentFixture projectJdkComboBox = findAll(ComponentFixture.class, byXpath("//div[@accessiblename='Project SDK:' and @class='JPanel']")).get(0);`

**Error msg details:**
`Wrapped org.assertj.swing.exception.ComponentLookupException: Unable to find component using matcher org.assertj.swing.core.NameMatcher[name='javax.swing.JPanel[,91,5,491x30,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]', type=javax.swing.JComboBox, requireShowing=true].`

<img width="731" alt="Snímek obrazovky 2021-10-02 v 19 43 47" src="https://user-images.githubusercontent.com/43820055/135726949-9518e334-78f5-45e8-b0e9-e3e052028b41.png">

**Comment by nizienko** [comment]
Thanks for the issue! The problem here is that when you want to use `ComboBoxFixture` you have to define a locator to the `Combobox` component instead of `JPanel` in your example. When `ComboboxFixture` is initialized it creates a custom `CellReader` to be able to read text in its items which is not applieble for JPanel.

So, could you please try this locator?
```
ComponentFixture projectJdkComboBox = comboBox(byXpath("//div[@accessiblename='Project SDK:' and @class='JPanel']/div[@class='JdkComboBox']"));

```

**Comment by zcervink** [comment]
@nizienko Thank you very much for help, your locator is working without issue.
