### ISSUE TITLE
StepLogger does not generate any output

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#110]
I have integrated the StepLogger and it seems it does not produce any outcome.

I have registered it before running any test
`StepWorker.registerProcessor(new StepLogger());`

I have added the steps into my code
`step("abcd....", () -> {............});`

**Comment by nizienko** [comment]
> @nizienko maybe I am doing something wrong, maybe I forget to add some code to activate it properly.

It seems to me that everything is fine. Could you please check if you have a log config in your resource directory. If not, please try to add this [log4j2 config](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/ui-test-example/src/test/resources/log4j2.xml)?
