### ISSUE TITLE
Integrate the step() logs directly into the waitFor()

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#111]
- it would be great to have logs from StepLogger when it is waiting for something in the waitFor() method - what we are waiting for, details about attempts to make the condition true and stop waiting etc.

**Comment by zcervink** [comment]
@nizienko I think this issue should be closed, I have found the integretion in the recently released 0.11.8 (but I do not know, if it is complete or not).

**Comment by nizienko** [comment]
> @nizienko I think this issue should be closed, I have found the integration in the recently released 0.11.8 (but I do not know, if it is complete or not).

yes, thank you for reminding me of this. It should work via `description` argument.
