### ISSUE TITLE
Error running with headless Android Studio

### ISSUE THREAD

**Issue by li-richard** [JetBrains/intellij-ui-test-robot#119]
I'm trying to run this robot with AS in an AWS EC2 instance, loosely following the headless example given in the Github Actions workflow, but I'm running into an error starting the IDE with `runIdeForUiTests`.

```
com.intellij.diagnostic.PluginException: Fatal error initializing 'com.intellij.ide.ui.LafManager' [Plugin: com.intellij]
```

This seems like it stems from using the wrong java runtime, but I am using the runtime bundled with the IDE:
```
* What went wrong:
Execution failed for task ':runIdeForUiTests'.
> Process 'command '/usr/local/AI-202.7660.26.42.7322048-android-studio/jre/bin/java'' finished with non-zero exit value 3
```
OS info:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Any idea what is going wrong here, and what I can do to get it working?

**Comment by li-richard** [comment]
Was able to fix by installing the `fontconfig` package with `yum install fontconfig`

**Comment by nizienko** [comment]
Thanks for letting know!
