### ISSUE TITLE
The Remote-Robot framework does not support native parts of the IntelliJ Idea

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#17]
- some part of the IntelliJ Idea are on some platforms native and not accessible using the RR framework
- see the top menu on OX X:
<img width="601" alt="img" src="https://user-images.githubusercontent.com/43820055/104309824-11e53a00-54d3-11eb-8f7b-bda3aa36806c.png">

**Comment by nizienko** [comment]
Hello, thanks for the issue. We are working on separate library with basic fixtures and I believe we going to publish it soon. We expecting it will contains methods to work with native menu via `osascript` which we use in our internal test project

**Comment by nizienko** [comment]
Hello,
could you please try [JMenuBarFixture](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/remote-fixtures/src/main/kotlin/com/intellij/remoterobot/fixtures/JMenuBarFixture.kt) which uses `osascript` to work with native mac menu

**Comment by zcervink** [comment]
@nizienko I tried to use that fixture, but I am not able to create instance on OS X (probably I need to use another approach because of the native parts on OS X). When I use:

`JMenuBarFixture jMenuBarFixture = remoteRobot.find(JMenuBarFixture.class, Duration.ofSeconds(10));`

I get an error:

`default locator is not defined for class com.intellij.remoterobot.fixtures.JMenuBarFixture`

**Comment by mkfl3x** [comment]
@zcervink could you try following code, please:
`remoteRobot.find(JMenuBarFixture.class, JMenuBarFixture.Companion.byType(), Duration.ofSeconds(10));`

**Comment by zcervink** [comment]
@mkfl3x I have an important update. I have tried the JPopupMenuFixture (not native parts of IntelliJ on OS X) and it works without any issue. I have open context menu and after that the following code navigates and clicks as expected. Well, the JMenuBarFixture does not address the right process/IntelliJ instance.

```
JPopupMenuFixture menu = remoteRobot.find(JPopupMenuFixture.class, JPopupMenuFixture.Companion.byType(), Duration.ofSeconds(10));
menu.select("New", "File");
```

**Comment by zcervink** [comment]
@mkfl3x @nizienko I have discussed this issue with my team - this issue is caused probably by wrong name of the IntelliJ used to run the UI tests (the name is generated in the [JMenuBarFixture](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/remote-fixtures/src/main/kotlin/com/intellij/remoterobot/fixtures/JMenuBarFixture.kt) class). In my case (and I think it will be in all cases), the IntelliJ is name '**Main**'. I think it will be really easy to fix.

<img width="917" alt="Snímek obrazovky 2021-09-01 v 20 12 19" src="https://user-images.githubusercontent.com/43820055/131722493-b4473fb4-4cd3-47c1-9595-85d567083df5.png">

**Comment by nizienko** [comment]
@zcervink Thanks for the investigation, seems that processName='Main' when we run idea with gradle. We will think how to handle this.

**Comment by gsaslis** [comment]
Hello @bric3, 

I am facing the same issue as I also can't make the native menu bar and sheets show up, despite having set: 

```
        systemProperty("ide.mac.message.dialogs.as.sheets", "false")
        systemProperty("apple.laf.useScreenMenuBar", "false")
```

Would you happen to know if this is still the recommended way to go about this ?

**Comment by nizienko** [comment]
Do you mean you want to disable the Mac native menu and file chooser? Then these properties are correct. Check how we defined it in [our test project ](https://github.com/JetBrains/intellij-ui-test-robot/blob/dcde1033a2f6dc335c98c5c668ff884019bc27ce/ui-test-example/build.gradle#L60)

**Comment by gsaslis** [comment]
Thank you @nizienko !

Yes, that is exactly how they have been defined in [Our project](https://github.com/cytechmobile/radicle-jetbrains-plugin/blob/feat/16_ui_tests/build.gradle.kts#L130) as well, but the native menu still shows up

**Comment by nizienko** [comment]
@gsaslis Indeed, just checked that `apple.laf.useScreenMenuBar` flag doesn't work.
I've found another one `jbScreenMenuBar.enabled=false`, seems it is more reliable.
I'm going to fix this info in the docs, thanks for pointing at this.

**Comment by gsaslis** [comment]
@nizienko I'm trying with both but neither seems to be having any effect...

could I please ask you to send me a screenshot of how it looks like on your machine when it is enabled?

**Comment by nizienko** [comment]
@gsaslis That's really strange. It seems we have to set both properties to false. I'm not sure that this is ok and asked about this in the corresponding [issue](https://youtrack.jetbrains.com/issue/IDEA-286996/useScreenMenuBarfalse-no-longer-effective#focus=Comments-27-6325387.0-0)

**Comment by gsaslis** [comment]
thanks @nizienko - setting both (!) to false did the trick... apologies I should have spotted that myself earlier!

**Comment by bric3** [comment]
Ah thanks for the update, this seem to have changed indeed.
This question might surface again with the new UI ?
