### ISSUE TITLE
Add a disclaimer about `com.intellij.remoterobot:remote-fixtures:1.1.18` being older than 0.11.13

### ISSUE THREAD

**Issue by bric3** [JetBrains/intellij-ui-test-robot#179]
This is very very disconcerting. Versions 1.1.17 and 1.1.18 are actually older than 0.11.
This is confusing tools that are using semver.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/803621/161633276-64ecf015-31d7-41b5-98ff-9559780e68b5.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/803621/161633349-b85196c7-e3eb-4197-a39d-08fd5e97d47e.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/803621/161633467-3273a801-7cb4-4389-abd7-facf705011a3.png">

**Comment by nizienko** [comment]
Versions 1.* were published by mistake. I've removed them. Thanks for pointing on the issue!

**Comment by bric3** [comment]
Let's close the issue then 
Thanks
