### ISSUE TITLE
Is it possible for switch the classloader in Rhino code?

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/intellij-ui-test-robot#185]
AFAICS Rhino executed via `com.intellij.remoterobot.RemoteRobot#callJs(java.lang.String, boolean)` (or `runJs`) is executed with `PluginClassLoader` for `Robot server` as context classloader. Attempt to `setContextClassLoader` to the `PluginClassLoader` of the tested plugin's don't seem to work:

Rhino code:
```js
  const pluginId = PluginId.getId('com.virtuslab.git-machete');
  const pluginClassLoader = PluginManagerCore.getPlugin(pluginId).getPluginClassLoader();
  Thread.currentThread().setContextClassLoader(pluginClassLoader);
  const providerClass = Class.forName('com.virtuslab.gitmachete.frontend.ui.providerservice.SelectedGitRepositoryProvider'); // some class from my plugin
```

results in:

```
        java.lang.Throwable: Wrapped java.lang.ClassNotFoundException: com.virtuslab.gitmachete.frontend.ui.providerservice.SelectedGitRepositoryProvider
 PluginClassLoader(plugin=PluginDescriptor(name=Robot server, id=com.jetbrains.test.robot-server-plugin, 
descriptorPath=plugin.xml, path=/tmp/ide-probe/instances/intellij-instance-2022.1--QLOZN9sdT3iaH2Vwk9Djew/plugins/robot-server-plugin, 
version=0.11.13, package=null, isBundled=true), packagePrefix=null, instanceId=20, state=active)
```

So it seems that Rhino uses Robot server's `PluginClassLoader`, no matter what `setContextClassLoader` points to. Is there any way around that?

**Comment by nizienko** [comment]
Hi, can you try to do it this way?
```
  const pluginId = PluginId.getId('com.virtuslab.git-machete');
  const pluginClassLoader = PluginManagerCore.getPlugin(pluginId).getPluginClassLoader();
  const providerClass = Class.forName('com.virtuslab.gitmachete.frontend.ui.providerservice.SelectedGitRepositoryProvider', true, pluginClassLoader); // some class from my plugin
```

**Comment by PawelLipski** [comment]
Yes! I can alternatively load a single class explicitly pointing to `pluginClassLoader` also by:
```js
  const providerClass = pluginClassLoader.loadClass('com.virtuslab.gitmachete.frontend.ui.providerservice.SelectedGitRepositoryProvider', true, pluginClassLoader); // some class from my plugin
```

but what I'm aiming at is to switch the **default classloader** used by Rhino! I tried `Thread.currentThread().setContextClassLoader(pluginClassLoader);` but to now avail, Rhino still seems to use the classloader associated with *Robot Server* plugin, not the plugin I've pointed to ☹️

**Comment by PawelLipski** [comment]
So I can provide a workaround by using more reflection (relying on `Class` and `Method` objects in Rhino code)... but curious if it's possible to just re-wire Rhino to use a different classloader completely 🤔

**Comment by nizienko** [comment]
I've tried to pass plugin classloader to rhino execution context and unfortunately it failed with [Loader can not resolve Rhino classes](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Context.java#L2344) error.
As for `setContextClassLoader` way, seems that Rhino caches it and keeps using the one was set on context creating. And if not I guess we would have the same error.
It might work if we run Robot Server not as a plugin but in the premain of Idea launching somewhere on early stage and it would be loaded by classloader which would be an ancestor for all plugin classloaders. But I guess it's to much for this task
