### ISSUE TITLE
Functions isPathExists(), clickPath() from JTreeFixture stop working with update to 0.11.14 (PathNotFoundException)

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#194]
- **Issue appear after update to Remote-Robot 0.11.14, version 0.11.13 and earlier are working without issues**
- I have some tests working with the Project Explorer (left panel in IntelliJ, there are project files, folder, whole structure)
- No issue when creating JTreeFixture fixture, no issue when expanding the tree using this fixture -> means fixture + some functions are without issue
- Functions isPathExists() and clickPath() -> PathNotFoundException even when path only one item - the root folder - in my case pe_java_project

<img width="561" alt="Snímek obrazovky 2022-06-27 v 10 38 39" src="https://user-images.githubusercontent.com/43820055/175897142-ed6e026d-a2e1-49b6-9907-3ec2b575feb3.png">

**Comment by shishovv** [comment]
We've changed the way how `JTreeFixture` reads the node values
So now in your case the root node of the tree will contain the path to the project
Try something like `tree.clickPath(tree.getValueAtRow(0), ...)` or create a subclass of `JTreeFixture` and replace the underneath fixture in contructor
```
runJs("""
        ctx.put("fixture", new JTreeFixture(robot, component));
        ctx.put("reader", new BasicJTreeCellReader())
""")
```

**Comment by zcervink** [comment]
@shishovv Thank you very much, I tried to use the first approach - I have replaced the first item in the path by the tree.getValueAtRow(0) and it worked. This issue is resolved, I close it.
