### ISSUE TITLE
The fun 'double' in the com.intellij.remoterobot.utils.Keyboard could not be invoked from Java code

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#21]
- 'double' is a reserved word in Java, so the fun 'double' cannot be invoked from Java code
- possible solution is to rename the function or add @JvmName("....") annotation

<img width="358" alt="Snímek obrazovky 2021-01-15 v 1 19 01" src="https://user-images.githubusercontent.com/43820055/104664634-090d8780-56d0-11eb-9a3e-7454aaf0c7ec.png">

**Comment by shishovv** [comment]
Fixed in `remote-fixtures:0.11.3.28`. `Keyboard#double` was renamed to `Keyboard#doubleKeyPress`
