### ISSUE TITLE
Module system errors with IntelliJ IDEA 2022.2

### ISSUE THREAD

**Issue by njbartlett** [JetBrains/intellij-ui-test-robot#211]
Using remote-robot version 0.11.15 with IntelliJ IDEA 2022.2 is failing with many errors from the Java module system on the IDE side. Note that IDEA 2022.2 now uses Java 17 as its internal JVM.

[Full log including stack trace is attached](https://github.com/JetBrains/intellij-ui-test-robot/files/9279800/idea_2022_2.log). This includes the following error:

```
Unable to make field private java.awt.Color javax.swing.text.JTextComponent.selectedTextColor accessible: module java.desktop does not "opens javax.swing.text" to unnamed module @f8f1074
```

I attempted to fix this by adding an `--add-opens` argument to the launcher as follows:

```java
    ideProcess = IdeLauncher.INSTANCE.launchIde(
        ideaPath,
        systemProperties,
        List.of("--add-opens=java.desktop/javax.swing.text=ALL-UNNAMED"),
        List.of(findRobotPluginPath(), pluginUnderTestPath),
        sandboxPath);
  }
```

However this did not have any effect.

**Comment by nizienko** [comment]
Hello, I've just found that we defined to old version of `robot-server-plugin` as a default version. I'll fix it. As a workaround could you please set `robot-server-plugin` version manually `ideDownloader.downloadRobotPlugin(tmpDir, "0.11.5")` in `indRobotPluginPath()`

**Comment by njbartlett** [comment]
Thanks for your reply. Actually in our project we don't use the provided IdeDownloader, since we have to download both IDEA and the plugin from an Artifactory server within our network (no external network access from Jenkins build nodes for security reasons).

Therefore we are already using the correct version of `robot-server-plugin`.

**Comment by nizienko** [comment]
Are you sure it is not too old? The exception was thrown from `XpathDataModelCreator.fillElement(XpathDataModelCreator.kt:90)` and now it should be with this [commit](https://github.com/JetBrains/intellij-ui-test-robot/commit/65a807b03343dee94a96c604fcbbf59c66ad97bb)

**Comment by njbartlett** [comment]
You were right, I apologize. I had an older version of the plugin cached by the build system (rookie mistake...). Thank you!

**Comment by nizienko** [comment]
Ok, good! Anyway, I'd like to keep this issue open until fix the default `robot-server-plugin` version in launcher
