### ISSUE TITLE
The Remote-Robot framework should provide IntelliJ Idea version

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#24]
- there should be a method/variable to provide current IntelliJ version while running the UI tests

**I write:** _private static RemoteRobot robot;_
**There should be an option such as**: _robot.ideaVersion_ **or** _robot.getIdeaVersion()_

**Comment by abrooksv** [comment]
Here is my extension method to get the major version (i.e. `202`)

```kotlin
fun RemoteRobot.ideMajorVersion() = callJs<Int>("com.intellij.openapi.application.ApplicationInfo.getInstance().getBuild().getBaselineVersion()")
```

**Comment by nizienko** [comment]
Now we have a method in the `remote-fixtures` library which actually do the same ).
`com.intellij.remoterobot.utils.UtilsKt#getIdeBuildNumber`
