### ISSUE TITLE
runIdeForUiTests no longer works with GitHub action

### ISSUE THREAD

**Issue by hstaudacher** [JetBrains/intellij-ui-test-robot#255]
I tried to enable ui tests for our IntelliJ plugin when I encountered problems. The wait for the ide step always times out.

So, I forked this repository and changed the `runTest` workflow to run on every push to `master` with the same result. On this project I've seen that the last time the tests ran was about 3 months ago. You can see the build outputs of my fork here: https://github.com/hstaudacher/intellij-ui-test-robot/actions/runs/3543076723

**Comment by nizienko** [comment]
Hi, thanks for the issue. I've updated java and gradle-plugin and that helped:
https://github.com/JetBrains/intellij-ui-test-robot/actions/runs/3543929306
Although there is a minor issue left on Windows - terminal was shown over the Idea

**Comment by hstaudacher** [comment]
Thanks, tested it and it's working now.
