### ISSUE TITLE
the browser cannot access 127.0.0.1:8082

### ISSUE THREAD

**Issue by tangculiji0612** [JetBrains/intellij-ui-test-robot#315]
Upgrade Intellij Idea from 2021.3.3 to 2022.2.3. Run the./gradlew ui-test-example:runIdeForUiTests command to bring up the Welcome to Intellij IDEA interface.  However, the browser cannot access 127.0.0.1:8082.  netstat -nlp | grep 8082 command did not query to the process, using the JDK and JBR version is 17, configuration: 
   systemProperty "robot-server.port", "8082"
    systemProperty "ide.mac.message.dialogs.as.sheets", "false"
    systemProperty "jb.privacy.policy.text", ""
    systemProperty "jb.consents.confirmation.enabled", "false"

**Comment by nizienko** [comment]
Hi, could you please clarify the version of `remote-robot-server plugin`, you can check it in Settings -> Plugins in idea which was lanched with `runIdeForUiTests`.

**Comment by diyangsx** [comment]
here is the configuration:
def remoteRobotVersion = "0.11.3"
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testImplementation 'com.intellij.remoterobot:remote-robot:' + remoteRobotVersion
    testImplementation 'com.intellij.remoterobot:remote-fixtures:' + remoteRobotVersion
}
The old version is 0.11.3. And I tried 0.11.16 and 0.11.17.

**Comment by nizienko** [comment]
can you try to set last robot-server version by configuring downloadRobotServer task?
```
downloadRobotServerPlugin  {
    version.set('0.11.18')
}
```

**Comment by tangculiji0612** [comment]
thanks
