### ISSUE TITLE
Skip the execution of the test case.

### ISSUE THREAD

**Issue by hekakahe** [JetBrains/intellij-ui-test-robot#342]
When I execute a test case, it often doesn't execute the test method, which happens all the time.
![Uploading image.png…]()

**Comment by nizienko** [comment]
hi, could you please check the image link, or provide some more information. But anyway I think that it is a test framework issue(junit ot tetng?)

**Comment by hekakahe** [comment]
hi,the test framework is junit ;this is my build.gradle
def remoteRobotVersion = "0.11.16"
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testImplementation 'com.intellij.remoterobot:remote-robot:' + remoteRobotVersion
    testImplementation 'com.intellij.remoterobot:remote-fixtures:' + remoteRobotVersion
    testImplementation 'com.squareup.okhttp3:logging-interceptor:4.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
    testImplementation project(path: ':util', configuration: 'testOutput')
    implementation fileTree(dir: 'lib', include: ['*.jar'])
    implementation fileTree(dir: '../libs', include: ['*.jar'])
}

runIdeForUiTests {
    systemProperty "robot-server.host.public", "true"
    systemProperty "robot-server.port", "8082"
    systemProperty "ide.mac.message.dialogs.as.sheets", "false"
    systemProperty "jb.privacy.policy.text", ""
    systemProperty "jb.consents.confirmation.enabled", "false"
}

downloadRobotServerPlugin {
    version.set('0.11.16')
}

test {
    useJUnitPlatform ()
}

**Comment by nizienko** [comment]
I would check that in the test class you are importing the correct @Test annotation from JUint5 and not from JUnit4.

**Comment by hekakahe** [comment]
All skipped test cases perform this task.
Task : linux:test FROM_CACHE 
this is my command  ./gradlew linux:runIdeForUiTests & ./gradlew linux:clean linux:test --tests
![image](https://github.com/JetBrains/intellij-ui-test-robot/assets/113006509/f2e96ecb-8c26-4afa-8f22-2db624d088ff)

**Comment by nizienko** [comment]
for me when I've tried this command I've got the error
```
Problem configuring task :ui-test-example:test from command line.
> No argument was provided for command-line option '--tests'.
```
don't use `--tests` parameter or specify a fllter value. I'm closing the issue as it is not related to the remote-robot
