### ISSUE TITLE
actionButton(byTooltipText("xx")) doesn't work anymore

### ISSUE THREAD

**Issue by henryju** [JetBrains/intellij-ui-test-robot#35]
Hi,

```
val remoteRobotVersion = "0.11.2"
val fixturesVersion = "1.1.18"
```

Not sure how to investigate, but I'm pretty sure it was working at some point. I updated multiple parts of our UI tests (like remote robot dependency), and now
`actionButton(byTooltipText("XXX"))`
doesn't work anymore.
To investigate, I tried to display:
`findAll(ActionButtonFixture::class.java, byXpath("//div[@class='ActionButton']")).forEach {println(it.tooltipText)}`
but it says "no tool tip" for all buttons. Looking at the robot "HTML tree" I can see that the buttons don't have a tooltipText attribute anymore:
![image](https://user-images.githubusercontent.com/281596/117291532-69872700-ae6f-11eb-8ac5-f2b5c7064fa1.png)

My workaround it to use:
`find(ActionButtonFixture::class.java, byXpath("//div[@tooltiptext='XXX' and @class='ActionButton']"))`

**Comment by nizienko** [comment]
Hello, 
Thanks for the issue. Indeed, in the last release we changed the `tooltipText` attribute to the lowercase. There is a warning in the release notes.  I hope we will not change these attributes anymore. Sorry for the troubles.

![image](https://user-images.githubusercontent.com/6516906/117297534-a276ca00-ae76-11eb-9595-a2afc485a26c.png)

It is handy to use developer tools in the browser to see all the attributes which can be used to create a locator.

**Comment by nizienko** [comment]
Sorry, I've just understood the problem with the old version of `remote-fixtures`. We will move its code to this project and publish the library very soon.

**Comment by henryju** [comment]
> It is handy to use developer tools in the browser to see all the attributes which can be used to create a locator

Good to know, thanks!

> We will move its code to this project and publish the library very soon.

That's great news!

**Comment by shishovv** [comment]
Please try to use `remote-fixtures:0.11.3.28`
