### ISSUE TITLE
How to test the page integrated by the plugin through JCEF

### ISSUE THREAD

**Issue by dongyzzzz** [JetBrains/intellij-ui-test-robot#350]
RemoteRobot cannot directly access the document object of JCEF integrated pages; How to test the page integrated by the plugin through JCEF😩

**Comment by nizienko** [comment]
Hi, you can use [JCefBrowserFixture](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/remote-fixtures/src/main/kotlin/com/intellij/remoterobot/fixtures/JCefBrowserFixture.kt) to work with the content of JCef browser

**Comment by HutorovaMN** [comment]
Привет! А можно подробней пытаюсь так 
 JCefBrowserFixture jcefFixture = remoteRobot.find(JCefBrowserFixture.class
                , JCefBrowserFixture.getMacLocator(), Duration.ofSeconds(10));
        
        Assertions.assertTrue(jcefFixture.hasText(" ")); И что то не видит он(
