### ISSUE TITLE
JListFixture collectItems returns truncated texts

### ISSUE THREAD

**Issue by victor-teles** [JetBrains/intellij-ui-test-robot#383]
Hi! I'm using JListFixture to collect items from the quick-fix panel:

```kotlin
find<JListFixture>(byXpath("//div[@class='MyList']"), timeout)
```

<img src="https://github.com/JetBrains/intellij-ui-test-robot/assets/78874691/532fed1f-75ad-40d7-9dc8-aee68465ec8b"  height="200" />

But on the test, the list only contains truncated texts, I've printed the text to the console and unfortunately, it's not just a visual bug:

<img src="https://github.com/JetBrains/intellij-ui-test-robot/assets/78874691/e4807e55-90e3-4cae-b955-928275653702"  height="250" />

### More details

Ran the tests on macOS Sonoma 14.1.2 (23B92)

`kotlin` `1.9.21`
`org.jetbrains.intellij` `1.16.1`

`com.intellij.remoterobot:remote-robot` `0.11.21`
`com.intellij.remoterobot:remote-fixtures` `0.11.21`
`org.junit.jupiter:junit-jupiter-api` `5.10.0`

**Comment by nizienko** [comment]
Seems sometimes it is not enough to use `list.width` in `JListTextCellReader`. We need to parameterize this value.
