### ISSUE TITLE
JCefBrowserFixture.findElements fails if targeted element is not within body

### ISSUE THREAD

**Issue by bauersimon** [JetBrains/intellij-ui-test-robot#408]
I found an edge case where [`JCefBrowserFixture.findElements`](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/remote-fixtures/src/main/kotlin/com/intellij/remoterobot/fixtures/JCefBrowserFixture.kt) can fail if the element targeted by the `XPath` expression is not within the body.

---

In my case, I wanted to query the `<title>` element from [example.com](http://example.com/). The `html` source for this is:
```html
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
...
```

I use the [JCefBrowser](https://plugins.jetbrains.com/docs/intellij/jcef.html) the following way:
```java
var browser = new JBCefBrowserBuilder().setEnableOpenDevToolsMenuItem(true).setUrl("www.example.com").build();
// Add browser to tool window.
```

Then I query the `<title>` element during testing via the remote robot and the fixture:
```java
var fixture = remoteRobot.find(JCefBrowserFixture.class, byXpath("//div[@class='JBCefOsrComponent']"), Duration.ofSeconds(5));
assertTrue(fixture.exist("//title[contains(text(), 'Example Domain')]"));
```

**Expected Behavior**

Should find and return the dom object corresponding to the `<title>`.

**Actual Behavior**

```
JCefBrowserFixture.JCEFScriptExecutionError: Failed to execute script ...
Caused by: No result from script ...
```
When opening the DevTools and looking at the console I see:
```js
findElements: by '//title[contains(text(), 'Example Domain')]'
found 1
Uncaught TypeError: Cannot read properties of null (reading 'childNodes')
    at Object.window.elementFinder.getPathTo ((index):1:1327)
    at Object.window.elementFinder.getPathTo ((index):1:1467)
    at Object.window.elementFinder.getPathTo ((index):1:1467)
    at Object.window.elementFinder.getPathTo ((index):1:1467)
    at new Elm ((index):1:204)
    at (index):1:1123
    at Array.map (<anonymous>)
    at Object.window.elementFinder.findElements ((index):1:1111)
    at (index):1:70
```

**Versions**

- IDEA: IntelliJ IDEA 2022.1 (Community Edition) Build #IC-221.5080.210, built on April 12, 2022
- Java: Runtime version: 11.0.14.1+1-b2043.25 amd64
- OS: Linux
- Remote Robot: [`v0.11.22`](https://github.com/JetBrains/intellij-ui-test-robot/releases/tag/v0.11.22)

---

I already did some investigating. Looks like the problem is [here](https://github.com/JetBrains/intellij-ui-test-robot/blob/a61d97a777fcd2eaacf3be23bb20c026c3614353/remote-fixtures/src/main/kotlin/com/intellij/remoterobot/fixtures/JCefBrowserFixture.kt#L38) where the JavaScript element finding is constructed and injected:
```js
$FINDER.getPathTo = (element) => { // Recursively walks up the element-parent-chain to construct the path.
    if (element === document.body) { // Base case never reached because "title" is not inside body, but inside "head".
        return element.tagName;
    }
    let ix = 0;
    const siblings = element.parentNode.childNodes; // Eventually reaches the "document" itself, which has no parent.
    ...
```

**Comment by nizienko** [comment]
@bauersimon thank you for the investigation! The problem was indeed there
