### ISSUE TITLE
Is it possible to run a robot on an already compiled plugin ? 

### ISSUE THREAD

**Issue by maoryf-lightrun** [JetBrains/intellij-ui-test-robot#462]
I am trying to run a robot over various versions of my intellij plugin, I couldn't find how to run with them the `robot-server` - is it even possible ? or only on a test compiled plugin it is possible ?

**Comment by nizienko** [comment]
Hi, you just need to add your compiled plugin to the plugins directory together with robot-server plugin and run ide.
You can use launcher which can do it for you - [example](https://github.com/JetBrains/intellij-ui-test-robot/blob/f89c6eb1976a10dbb9feff72fcb778716649c8f5/ide-launcher/src/test/java/com/intellij/remoterobot/launcher/LauncherJavaExampleTest.java#L52)
