### ISSUE TITLE
MyDialog child components have duplicates in the tree in 0.10.1

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/intellij-ui-test-robot#6]
In 0.10.1, dialogs classes are returning the same child components multiple times in the hierarchy:

DOM View:
<img width="1202" alt="Screen Shot 2020-12-23 at 10 31 25 AM" src="https://user-images.githubusercontent.com/8992246/103027070-0d4be800-450a-11eb-8b6b-ab299b735744.png">

UI Inspector:
<img width="470" alt="Screen Shot 2020-12-23 at 10 32 03 AM" src="https://user-images.githubusercontent.com/8992246/103027125-1e94f480-450a-11eb-873a-aa53931fc656.png">

Debugger View:
```
remoteRobot.findAll<JTextFieldFixture>(byXpath("//div[@accessiblename='Bucket Name:' and @class='JTextField']"))

result = {ArrayList@8072}  size = 3
 0 = {JTextFieldFixture@8074} 
  data$delegate = {SynchronizedLazyImpl@8078} "Lazy value not initialized yet."
  remoteRobot = {RemoteRobot@7020} 
  remoteComponent = {RemoteComponent@8079} 
   id = "6475acea-e311-477c-bba5-f507961384f4"
   className = "javax.swing.JTextField"
   name = null
   x = 98
   y = 0
   width = 400
   height = 30
 1 = {JTextFieldFixture@8075} 
  data$delegate = {SynchronizedLazyImpl@8082} "Lazy value not initialized yet."
  remoteRobot = {RemoteRobot@7020} 
  remoteComponent = {RemoteComponent@8083} 
   id = "a6256dda-9cce-4431-a466-a055bf922d0d"
   className = "javax.swing.JTextField"
   name = null
   x = 98
   y = 0
   width = 400
   height = 30
 2 = {JTextFieldFixture@8076} 
  data$delegate = {SynchronizedLazyImpl@8086} "Lazy value not initialized yet."
  remoteRobot = {RemoteRobot@7020} 
  remoteComponent = {RemoteComponent@8087} 
   id = "4caa1430-cb59-47ca-9f44-ac337513df45"
   className = "javax.swing.JTextField"
   name = null
   x = 98
   y = 0
   width = 400
   height = 30
```

Note: If I use the root `remoteRobot`, it finds 3. If I use findAll scoped to the IdeFrame, it only finds 2.

---

In 0.9.35:
DOM View:
<img width="1346" alt="Screen Shot 2020-12-23 at 10 27 15 AM" src="https://user-images.githubusercontent.com/8992246/103026768-72530e00-4509-11eb-8028-e04400af4a0a.png">

UI Inspector:
<img width="481" alt="Screen Shot 2020-12-23 at 10 26 08 AM" src="https://user-images.githubusercontent.com/8992246/103026694-4d5e9b00-4509-11eb-8858-57daf35907eb.png">

Debugger View:
<img width="479" alt="Screen Shot 2020-12-23 at 10 25 12 AM" src="https://user-images.githubusercontent.com/8992246/103026608-2a33eb80-4509-11eb-8a56-1a013fc5ed1a.png">

**Comment by nizienko** [comment]
Hello, the issue must be fixed in `0.10.2`
