### ISSUE TITLE
Trying to get SayHelloJavaTest to work... can't find ActionButton

### ISSUE THREAD

**Issue by cschar** [JetBrains/intellij-ui-test-robot#65]
Using Window10 with IntelliJ 2021.2 EAP (212.4037.50) as the testIDE...

When cloning and trying to run the first tests, It seemed the test could not find the 'more actions' element...

in kotlin/org/intellij/examples/simple/plugin/pages/WelcomeFrame.kt
I changed the code to 
```
    val moreActions
        get() = button(byXpath("More Actions", "//div[@accessiblename='More Actions' and @class='DropDownLink']"))

```
from the original 

```
 val moreActions
        get() = button(byXpath("More Action", "//div[@accessiblename='More Actions' and @class='ActionButton']"))

```

and it seemed to work...
!

p.s. is there any  chance of getting the latest 0.14 versions published to your repository?

https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/org/jetbrains/test/robot-server-plugin/

only shows up to version 0.10

Thank you!

**Comment by nizienko** [comment]
Thanks for the issue! I'll fix the tests.

You can find the latest versions [here](https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/intellij/remoterobot/robot-server-plugin/)(package has been changed since 0.11.x)
